# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main5.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 876)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nodeSet = QtWidgets.QGroupBox(self.centralwidget)
        self.nodeSet.setGeometry(QtCore.QRect(30, 20, 481, 151))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(14)
        self.nodeSet.setFont(font)
        self.nodeSet.setObjectName("nodeSet")
        self.label = QtWidgets.QLabel(self.nodeSet)
        self.label.setGeometry(QtCore.QRect(80, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.nodeSet)
        self.label_2.setGeometry(QtCore.QRect(160, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.adNode = QtWidgets.QSpinBox(self.nodeSet)
        self.adNode.setGeometry(QtCore.QRect(250, 50, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adNode.setFont(font)
        self.adNode.setObjectName("adNode")
        self.slotNode = QtWidgets.QSpinBox(self.nodeSet)
        self.slotNode.setGeometry(QtCore.QRect(250, 90, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.slotNode.setFont(font)
        self.slotNode.setObjectName("slotNode")
        self.btn1 = QtWidgets.QPushButton(self.nodeSet)
        self.btn1.setGeometry(QtCore.QRect(370, 110, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.adNodeSet = QtWidgets.QGroupBox(self.centralwidget)
        self.adNodeSet.setGeometry(QtCore.QRect(30, 210, 481, 161))
        self.adNodeSet.setTitle("")
        self.adNodeSet.setObjectName("adNodeSet")
        self.gridLayoutWidget = QtWidgets.QWidget(self.adNodeSet)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 9, 441, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(400, 380, 93, 28))
        self.btn2.setObjectName("btn2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 420, 451, 331))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(530, 110, 581, 521))
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setGeometry(QtCore.QRect(230, 780, 93, 28))
        self.nextBtn.setObjectName("nextBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nodeSet.setTitle(_translate("MainWindow", "Node Configuration"))
        self.label.setText(_translate("MainWindow", "Advertisement Node"))
        self.label_2.setText(_translate("MainWindow", "Slot Node"))
        self.btn1.setText(_translate("MainWindow", "Set"))
        self.btn2.setText(_translate("MainWindow", "Sst"))
        self.nextBtn.setText(_translate("MainWindow", "Next"))
        

